apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1toi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-1toi@sha256:596acfb3327537c3d5ff4788b0ae637ced426ac1bce4fa88b5648381f4f4cb4c
        name: my-nodejs
        resources: {}
status: {}
